
spring:
  application:
    name: sms-service

  h2:
    console:
      enabled: true

server:
  port: 9091

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost